spring:
  application:
      name: tlias-web-management

  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource\\
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456

mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
